main_keywords = [
    
]


keywords2 = [
    "drop shipping books",
    "drop shipping business reddit",
    "drop shipping business amazon",
    "dropshipping basics",
    "drop shipping boutique clothing",
    "drop shipping beauty products",
    "best drop shipping companies",
    "best drop shipping items",
    "best drop shipping websites",
    "blind drop shipping",
    "best dropshipping suppliers",
    "best dropshipping apps",
    "branded dropshipping",
    "business names for drop shipping",
    "best product for dropshipping",
    "best dropshipping course",
    "drop shipping course",
    "drop shipping coffee",
    "drop shipping clothing",
    "drop shipping companies usa",
    "drop shipping custom shirts",
    "drop shipping classes",
    "drop shipping checker",
    "drop shipping companies that work with etsy",
    "drop shipping cost",
    "can you make money drop shipping",
    "coffee drop shipping",
    "companies that do drop shipping",
    "candlefy candle drop shipping",
    "cbd drop shipping",
    "can you actually make money dropshipping",
    "can you do drop shipping on amazon",
    "clothing drop shipping",
    "cons of drop shipping",
    "drop shipping definition",
    "drop shipping def",
    "drop shipping discord",
    "drop shipping dog products",
    "drop shipping define",
    "drop shipping distributors",
    "dropshipping digital products",
    "drop shipping diapers",
    "drop shipping diagram",
    "drop shipping dhgate",
    "define drop shipping",
    "does drop shipping work",
    "digital drop shipping",
    "does amazon do drop shipping",
    "does etsy allow drop shipping",
    "does dropshipping actually work",
    "does drop shipping work reddit",
    "does dropshipping work in 2022",
    "do you pay taxes on drop shipping",
    "does drop shipping work in 2023",
    "drop shipping examples",
    "drop shipping explained",
    "drop shipping etsy",
    "drop shipping ebay",
    "drop shipping ecommerce",
    "drop shipping embroidery",
    "drop shipping electronics",
    "drop shipping easy",
    "drop shipping explained youtube",
    "drop shipping explanation",
    "ebay drop shipping",
    "etsy drop shipping",
    "what is dropshipping",
    "e commerce vs drop shipping",
    "ecommerce dropshipping",
    "example of drop shipping",
    "easy drop shipping business",
    "everything you need to know about drop shipping",
    "examples of drop shipping websites",
    "examples of drop shipping companies",
    "drop shipping for dummies",
    "drop shipping for beginners",
    "drop shipping for amazon",
    "drop shipping from temu",
    "drop shipping from alibaba",
    "drop shipping for shopify",
    "drop shipping for free",
    "drop shipping furniture",
    "drop shipping from aliexpress",
    "drop shipping for etsy",
    "free drop shipping website",
    "free dropshipping course",
    "fashiongo dropshipping",
    "free drop shipping",
    "furniture drop shipping",
    "factory fast drop shipping",
    "faire drop shipping",
    "free drop shipping companies",
    "fedex drop shipping locations",
    "facebook drop shipping",
    "drop shipping guide",
    "drop shipping guide reddit",
    "drop shipping greeting cards",
    "drop shipping golf balls",
    "drop shipping getting started",
    "drop shipping guide 2023",
    "drop shipping good or bad",
    "drop shipping godaddy",
    "drop shipping gifts",
    "drop shipping graph",
    "gelato drop shipping",
    "gift basket drop shipping",
    "good dropshipping products",
    "guide to dropshipping",
    "good dropshipping store names",
    "golf drop shipping",
    "giclee printing drop shipping",
    "getting started with dropshipping",
    "dropshipping with godaddy",
    "global drop shipping",
    "drop shipping how to start",
    "drop shipping how to",
    "drop shipping hair companies",
    "drop shipping home decor",
    "drop shipping hats",
    "drop shipping how does it work",
    "drop shipping hair",
    "drop shipping how to make money",
    "drop shipping how to get started",
    "drop shipping how much can you make",
    "how to do drop shipping on amazon",
    "how to start dropshipping on amazon",
    "how to drop shipping",
    "how to do drop shipping on shopify",
    "is dropshipping hard",
    "hhc dropshipping",
    "how to drop shipping on amazon",
    "drop shipping ideas",
    "drop shipping items",
    "drop shipping in 2023",
    "dropshipping io",
    "drop shipping income",
    "drop shipping items 2023",
    "drop shipping is also called",
    "drop shipping in spanish",
    "drop shipping illegal",
    "drop shipping is it worth it",
    "is drop shipping easy",
    "is dropshipping legal",
    "is dropshipping illegal",
    "is dropshipping worth it",
    "is dropshipping haram",
    "is drop shipping worth it reddit",
    "is dropshipping legit",
    "is dropshipping dead",
    "is drop shipping legal in australia",
    "drop shipping jobs",
    "drop shipping jewelry",
    "drop shipping jobs near me",
    "dropshipping journals",
    "drop shipping jobs remote",
    "drop shipping jewelry etsy",
    "drop shipping jobs online",
    "drop shipping jewellery",
    "drop shipping japan",
    "drop shipping jewellery uk",
    "jewelry drop shipping",
    "jm wholesale drop shipping",
    "japanese drop shipping",
    "jumia drop shipping",
    "japan drop shipping",
    "journal entry for drop shipping",
    "jobs in drop shipping",
    "jb drop shipping",
    "jjshouse drop shipping",
    "drop shipping kitchenware",
    "drop shipping knives",
    "drop shipping kya hai",
    "drop shipping kuwait",
    "drop shipping kya hoti hai",
    "drop shipping kya h",
    "drop shipping kaise karte hain",
    "drop shipping ka matlab",
    "drop shipping kenya",
    "drop shipping king",
    "kiwi drop shipping",
    "kogan drop shipping",
    "kevin o'leary dropshipping",
    "keys to drop shipping",
    "keychain dropshipping",
    "korea drop shipping",
    "kayak drop shipping",
    "kinds of drop shipping",
    "drop shipping in kenya",
    "drop shipping legal",
    "drop shipping lifestyle",
    "drop shipping logo",
    "drop shipping llc",
    "drop shipping legit",
    "drop shipping login",
    "drop shipping lessons",
    "drop shipping là gì",
    "drop shipping learning",
    "drop shipping legal issues",
    "how to learn dropshipping",
    "lazada drop shipping",
    "learn how to do drop shipping",
    "leverage drop shipping",
    "list of drop shipping companies",
    "luxury drop shipping",
    "low cost drop shipping",
    "laser cutting drop shipping",
    "local drop shipping",
    "luke belmar dropshipping",
    "drop shipping manufacturers",
    "drop shipping merchandise",
    "drop shipping model",
    "drop shipping medical supplies",
    "drop shipping money",
    "drop shipping merch",
    "drop shipping mentor",
    "drop shipping marketing",
    "drop shipping made easy",
    "meaning of drop shipping",
    "how to make money dropshipping",
    "most successful drop shipping companies",
    "million dollar drop shipping",
    "mirage pet products drop shipping",
    "mpix drop shipping",
    "most profitable dropshipping products",
    "meaning of drop shipping business",
    "how to make money dropshipping on amazon",
    "merch drop shipping",
    "drop shipping near me",
    "drop shipping names",
    "drop shipping naics code",
    "drop shipping name generator",
    "drop shipping naics",
    "dropshipping niches",
    "drop shipping notebooks",
    "drop shipping no inventory",
    "drop shipping nike products",
    "naics code for drop shipping",
    "nordstrom drop shipping",
    "netsuite drop shipping",
    "nike drop shipping",
    "names for a drop shipping business",
    "number 1 dropshipping company",
    "dropshipping niche",
    "nz post drop shipping",
    "new zealand drop shipping",
    "noon drop shipping",
    "drop shipping on amazon",
    "drop shipping on etsy",
    "drop shipping on ebay",
    "drop shipping on shopify",
    "drop shipping on tiktok",
    "drop shipping on mercari",
    "drop shipping on amazon reddit",
    "drop shipping on etsy reddit",
    "drop shipping opportunities",
    "drop shipping on amazon for beginners",
    "online drop shipping",
    "on demand drop shipping",
    "oberlo dropshipping",
    "online drop shipping business for sale",
    "online store drop shipping",
    "online drop shipping business meaning",
    "oliver goehler drop shipping",
    "online boutique drop shipping",
    "organic drop shipping",
    "odoo drop shipping",
    "drop shipping print on demand",
    "drop shipping platforms",
    "drop shipping pet products",
    "drop shipping profit margin",
    "drop shipping printing companies",
    "drop shipping process",
    "drop shipping providers",
    "drop shipping profit",
    "drop shipping photo prints",
    "print on demand drop shipping",
    "dropshipping pros and cons",
    "dropshipping products",
    "print on demand drop shipping uk",
    "private label wine drop shipping",
    "printing drop shipping",
    "private label drop shipping",
    "printify dropshipping",
    "pet supplies drop shipping",
    "print on demand canvas drop shipping",
    
    # Keywords for "making money with Airbnb"
    "Airbnb+hosting+strategies", "Professional+Airbnb+management", "Airbnb+income+optimization",
    "Superhost+success+tips", "Airbnb+property+management", "Luxury+Airbnb+rentals",
    "Expert+Airbnb+hosting", "High-quality+Airbnb+listings", "Premium+Airbnb+services",
    "Airbnb+hosting+professionalism", "Professional+Airbnb+photography", "Airbnb+hospitality+excellence",
    "Pro+Airbnb+host+advice", "Airbnb+business+professionalism", "Airbnb+rental+management",
    "Top-tier+Airbnb+experiences", "Airbnb+host+professionalism", "Airbnb+property+investment",
    "5-star+Airbnb+reviews", "Airbnb+property+styling", "Airbnb+host+certification",
    "Airbnb+concierge+services", "Airbnb+property+development", "Airbnb+business+growth",
    "Airbnb+customer+satisfaction", "Airbnb+host+training", "Airbnb+luxury+accommodation",
    "Airbnb+income+expertise", "Airbnb+property+maintenance", "Airbnb+host+branding",

    # Keywords for "Amazon FBA"
    "Amazon+FBA+expert+advice", "Professional+FBA+strategies", "FBA+business+growth",
    "Amazon+FBA+success+stories", "Pro+Amazon+FBA+techniques", "FBA+product+sourcing+excellence",
    "Amazon+FBA+marketing+professionalism", "Amazon+FBA+inventory+management",
    "FBA+profitability+optimization", "FBA+private+label+mastery", "Amazon+FBA+customer+service",
    "Amazon+FBA+product+research", "FBA+financial+management", "FBA+listing+optimization",
    "Amazon+FBA+branding+strategies", "FBA+seller+professionalism", "Amazon+FBA+fulfillment+expertise",
    "FBA+shipping+and+logistics", "Amazon+FBA+PPC+advertising", "FBA+product+launch+tactics",
    "Amazon+FBA+account+management", "FBA+inventory+planning", "Amazon+FBA+legal+compliance",
    "FBA+seller+tools+and+software", "Amazon+FBA+expansion+tactics", "FBA+profit+margins",
    "Amazon+FBA+inventory+storage", "FBA+competitive+analysis", "FBA+international+markets",
    "Amazon+FBA+entrepreneurship",

    # Keywords for "Dropshipping"
    "Dropshipping+business+professionalism", "Professional+dropshipping+strategies",
    "Dropshipping+supplier+relations", "Expert+dropshipping+techniques", "Dropshipping+product+selection",
    "Dropshipping+inventory+management", "High-quality+dropshipping+products", "Dropshipping+branding+excellence",
    "Dropshipping+store+optimization", "Top-tier+dropshipping+customer+service", "Dropshipping+fulfillment+expertise",
    "Dropshipping+marketing+professionalism", "Dropshipping+software+solutions", "Dropshipping+profit+margins",
    "Dropshipping+pricing+strategies", "Dropshipping+supplier+vetting", "Dropshipping+product+research",
    "Dropshipping+order+processing", "Dropshipping+payment+processing", "Dropshipping+legal+compliance",
    "Dropshipping+customer+retention", "Dropshipping+return+policies", "Dropshipping+analytics+and+reporting",
    "Dropshipping+advertising+campaigns", "Dropshipping+market+analysis", "Dropshipping+e-commerce+platforms",
    "Dropshipping+business+growth", "Dropshipping+customer+satisfaction", "Dropshipping+scalability",
    "Dropshipping+supply+chain+management"

    # Keywords for 'Video+Editing'
    "Professional+video+editing", "Video+editing+software", "Video+editing+techniques", "Advanced+video+editing",
    "Video+editing+tutorials", "Creative+video+editing", "Video+editing+for+beginners", "Video+editing+services",
    "Video+editing+tools", "Video+editing+workflow", "Video+editing+best+practices", "Video+editing+expertise",
    "Video+editing+training", "Video+editing+career", "Video+editing+portfolio", "Video+editing+professionalism",
    "Video+editing+software+reviews", "Video+editing+certification", "Video+editing+skills", "Video+editing+consulting",
    "Video+editing+business", "Video+editing+job+opportunities", "Video+editing+freelancing", "Video+editing+industry",
    "Video+editing+portfolio+development", "Video+editing+courses", "Video+editing+masterclass",
    "Video+editing+expert+advice", "Video+editing+portfolio+building", "Video+editing+professional+development",

    # Keywords for 'Youtube+Automations'
    "YouTube+automations+tools", "Automate+YouTube+channel", "YouTube+channel+optimization",
    "YouTube+video+automation", "YouTube+content+management", "YouTube+automations+strategies",
    "YouTube+marketing+automation", "YouTube+audience+growth+automation", "YouTube+monetization+automations",
    "Automate+YouTube+analytics", "YouTube+SEO+automation", "YouTube+upload+automation", "YouTube+playlist+automation",
    "Automate+YouTube+comments", "YouTube+engagement+automation", "YouTube+content+scheduling",
    "YouTube+advertising+automations", "YouTube+live+streaming+automation", "YouTube+automated+thumbnail+creation",
    "YouTube+promotion+automations", "YouTube+algorithm+optimization", "YouTube+subscriber+management",
    "Automate+YouTube+content+creation", "YouTube+marketing+analytics+automation", "YouTube+data+analysis+automations",
    "YouTube+reporting+automations", "YouTube+channel+growth+automations", "YouTube+audience+engagement+automations",
    "Automate+YouTube+audience+research", "YouTube+ad+campaign+automations",

    # Keywords for 'Online+coaching'
    "Professional+online+coaching", "Online+coaching+services", "Online+coaching+programs",
    "Certified+online+coach", "Online+coaching+platforms", "Online+coaching+certification",
    "Online+coaching+for+success", "Online+coaching+expertise", "Online+coaching+career",
    "Online+coaching+professionalism", "Online+coaching+tools", "Online+coaching+strategies",
    "Online+coaching+business", "Online+coaching+courses", "Online+coaching+mentorship",
    "Online+coaching+industry", "Online+coaching+job+opportunities", "Online+coaching+client+management",
    "Online+coaching+portfolio", "Online+coaching+best+practices", "Online+coaching+certification+programs",
    "Online+coaching+market", "Online+coaching+success+stories", "Online+coaching+testimonial",
    "Online+coaching+networking", "Online+coaching+expert+advice", "Online+coaching+professional+development",
    "Online+coaching+training", "Online+coaching+techniques", "Online+coaching+ethical+standards",

    # Keywords for 'Online+marketing'
    "Professional+online+marketing", "Online+marketing+strategies", "Online+marketing+expertise",
    "Online+marketing+services", "Online+marketing+campaigns", "Online+marketing+tools",
    "Online+marketing+automation", "Online+marketing+analytics", "Online+marketing+consulting",
    "Online+marketing+career", "Online+marketing+best+practices", "Online+marketing+portfolio",
    "Online+marketing+certification", "Online+marketing+business", "Online+marketing+courses",
    "Online+marketing+job+opportunities", "Online+marketing+freelancing", "Online+marketing+industry",
    "Online+marketing+portfolio+development", "Online+marketing+agency", "Online+marketing+advertising",
    "Online+marketing+reporting", "Online+marketing+strategies+for+success", "Online+marketing+campaign+management",
    "Online+marketing+target+audience", "Online+marketing+content+creation", "Online+marketing+analytics+tools",
    "Online+marketing+social+media", "Online+marketing+search+engine+optimization",
    "Online+marketing+email+marketing", "Online+marketing+affiliate+marketing",
]